# Generated by Django 4.2 on 2024-10-01 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedure', '0009_alter_customer_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=16)),
                ('Number', models.DecimalField(blank=True, decimal_places=0, max_digits=16)),
                ('status', models.CharField(choices=[('اولیه', 'اولیه'), ('تسویه شده', 'تسویه شده'), ('کنسل شده', 'کنسل شده')], default='اولیه', max_length=50)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.CharField(editable=False, max_length=20)),
                ('updated_at', models.CharField(editable=False, max_length=20)),
                ('Procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedure.procedure')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedure.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=16)),
                ('status', models.CharField(choices=[('اولیه', 'اولیه'), ('ثبت شده', 'ثبت شده'), ('دریافت شده', 'دریافت شده'), ('سر رسیده', 'سر رسیده'), ('برگشت خورده', 'برگشت خورده'), ('پاس شده', 'پاس شده')], default='اولیه', max_length=50)),
                ('sub_date', models.CharField(blank=True, max_length=20)),
                ('due_date', models.CharField(blank=True, max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.CharField(editable=False, max_length=20)),
                ('updated_at', models.CharField(editable=False, max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedure.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
