# Generated by Django 4.2 on 2024-10-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='Number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='Procedure',
            new_name='procedure',
        ),
        migrations.AddField(
            model_name='bill',
            name='factor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='bills.factor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
