# Generated by Django 5.1.1 on 2024-09-24 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_info_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن را به درستی وارد کنید.', regex='^\\d{11}$')]),
        ),
    ]
