# Generated by Django 4.2 on 2024-09-26 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='این فیلد را به فارسی وارد کنید.', regex='^[\\u0600-\\u06FF\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='این فیلد را به فارسی وارد کنید.', regex='^[\\u0600-\\u06FF\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن را به درستی وارد کنید.', regex='^09\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'نام کاربری تکراری است.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='نام کاربری تنها می\u200cتواند شامل حروف انگلیسی، اعداد، _ و نقطه باشد.', regex='^[a-zA-Z0-9_.]+$')]),
        ),
    ]
