# Generated by Django 4.2 on 2024-09-26 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, validators=[django.core.validators.RegexValidator(message='این فیلد را به فارسی وارد کنید.', regex='^[\\u0600-\\u06FF\\s]+$')]),
        ),
    ]
