# Generated by Django 5.1.1 on 2024-09-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead',
            field=models.CharField(choices=[('دیسپچ سرو', 'دیسپچ سرو'), ('دیسپچ سپیدز', 'دیسپچ سپیدز'), ('مشتریان', 'مشتریان'), ('اینترنت', 'اینترنت'), ('وبسایت', 'وبسایت'), ('راه\u200cانداز', 'راه\u200cانداز')], default='مذاکره', max_length=50),
        ),
    ]
