# Generated by Django 4.2 on 2024-09-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0005_status_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
