# Generated by Django 4.2 on 2024-09-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0006_procedure_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='name',
            new_name='comment',
        ),
    ]
