# Generated by Django 4.2 on 2024-09-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0007_rename_name_procedure_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='created_at',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='updated_at',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='updated_at',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
