# Generated by Django 4.2 on 2024-10-06 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procedure', '0009_alter_customer_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.CharField(editable=False, max_length=20)),
                ('updated_at', models.CharField(editable=False, max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedure.customer')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedure.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
