# Generated by Django 4.2 on 2024-10-06 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0010_staff_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedure.staff'),
        ),
    ]
