# Generated by Django 4.2 on 2024-10-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0011_alter_demo_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedure.procedure'),
        ),
    ]
