# Generated by Django 4.2 on 2024-10-14 08:20

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0012_alter_demo_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
